name: Discord Notification

on:
  push:
    branches:
      - '*'

jobs:
  send_discord_message:
    name: Send Discord Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send Discord message
        uses: appleboy/discord-action@master
        with:
          webhook_id: 1153890642204819531
          webhook_token: j0zu3_SX2a3rdDgNRSH00I1TcFVMaTKRgPzpLMYZSC3Z3ZkxkuzosrXGIBVxeTMo8J-6
          message: "Push event detected on branch ${{ github.ref }} by ${{ github.actor }}."

